version: "3.8"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8-community
    volumes:
      - ./data:/opt/sonarqube/data
    ports:
      - "9000:9000"
    networks:
      - app-network

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sonarqube
      - jenkins
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
